# Data Download

## Overview :-

**What this notebook does :**
- downloads the M5 Walmart dataset from Kaggle into the project's raw data folder
- checks that the files needed for the project are there
- finds out which of the downloaded files are really needed

**Approach followed :**
- the data is downloaded with [kagglehub](https://github.com/Kaggle/kagglehub), Kaggle's own Python library
- the raw files are never edited after download, every later step reads them and saves its results somewhere else

**Steps :**
- 1 . Import Required Modules
- 2 . Settings
- 3 . Kaggle Login
- 4 . Download the Data
- 5 . Check the Downloaded Files

**Reads / Writes :**
- **Reads :** [M5 Forecasting - Accuracy (Kaggle)](https://www.kaggle.com/competitions/m5-forecasting-accuracy/data)
- **Writes :** `data/M5-Walmart-Sales-Forecasting/`

# 1 . Import Required Modules :-

In [1]:
import os                                   # import os library for working with folders and files
from getpass import getpass                 # import getpass to type the Kaggle token without showing it
import pandas as pd                         # import pandas library for reading the data

import warnings                             # import warnings to ignore future warnings
warnings.filterwarnings('ignore')

import kagglehub                            # import kagglehub library for downloading Kaggle data

# 2 . Settings :-

- **DATA_DIR :** folder where the raw data is saved (same as `raw_dir` in `config/stockwise.yaml`)
- **COMPETITION :** name of the competition on Kaggle, taken from the end of its web address
- **FILES :** the 5 files Kaggle gives for this competition, used to check that the download is complete

In [2]:
DATA_DIR = '../data/M5-Walmart-Sales-Forecasting/'                       # raw data folder
COMPETITION = 'm5-forecasting-accuracy'                                   # Kaggle competition name
FILES = ['calendar.csv', 'sales_train_evaluation.csv', 'sales_train_validation.csv',
         'sample_submission.csv', 'sell_prices.csv']                      # all files of the competition

# 3 . Kaggle Login :-

Kaggle gives competition data only to logged in users who accepted the competition rules. One time setup :

- open the [competition page](https://www.kaggle.com/competitions/m5-forecasting-accuracy) and click **Join Competition** to accept the rules
- go to **Kaggle -> Settings -> API -> Create New Token** and copy the token
- save it in a file named `.env` in the project folder, as one line : `KAGGLE_API_TOKEN=<your token>`

The cell below reads the token from `.env`. If there is no `.env` file, a box opens to paste the token.
- `.env` is listed in `.gitignore`, so the token never goes to git
- never type the token directly inside a cell, the notebook goes to git
- if the files are already in `DATA_DIR`, no login is needed

In [3]:
if all(os.path.exists(DATA_DIR + i) for i in FILES):                     # login is needed only for the download
    print("Data already downloaded, login not needed")
else:
    if os.path.exists('../.env'):                                         # read the token from the .env file
        for line in open('../.env'):
            if '=' in line:
                name, value = line.strip().split('=', 1)                  # KAGGLE_API_TOKEN=<token>
                os.environ[name] = value
    if 'KAGGLE_API_TOKEN' not in os.environ:                              # no .env file, so ask for the token
        os.environ['KAGGLE_API_TOKEN'] = getpass("Paste your Kaggle API token : ")
    print("Logged in as : ", kagglehub.whoami()['username'])              # check the token with Kaggle

Kaggle credentials successfully validated.

Logged in as :  gujurialekha

# 4 . Download the Data :-

The download (about **450 MB**) runs only when the files are not already in the folder, so running the notebook again does not download the data again.

In [4]:
os.makedirs(DATA_DIR, exist_ok=True)                                      # create the folder if it is not there

if all(os.path.exists(DATA_DIR + i) for i in FILES):                      # skip the download if the files are already there
    print("Data already downloaded in : ", DATA_DIR)
else:
    kagglehub.competition_download(COMPETITION, output_dir=DATA_DIR)      # download and unzip the competition files
    print("Data downloaded to : ", DATA_DIR)

Downloading to ../data/M5-Walmart-Sales-Forecasting/m5-forecasting-accuracy.archive...

  0%|          | 0.00/45.8M [00:00<?, ?B/s]

  2%|▏         | 1.00M/45.8M [00:01<00:59, 786kB/s]

  4%|▍         | 2.00M/45.8M [00:01<00:30, 1.48MB/s]

  7%|▋         | 3.00M/45.8M [00:01<00:21, 2.07MB/s]

  9%|▊         | 4.00M/45.8M [00:02<00:16, 2.71MB/s]

 11%|█         | 5.00M/45.8M [00:02<00:13, 3.22MB/s]

 13%|█▎        | 6.00M/45.8M [00:02<00:11, 3.70MB/s]

 15%|█▌        | 7.00M/45.8M [00:02<00:10, 3.99MB/s]

 17%|█▋        | 8.00M/45.8M [00:02<00:09, 4.19MB/s]

 20%|█▉        | 9.00M/45.8M [00:03<00:09, 4.26MB/s]

 22%|██▏       | 10.0M/45.8M [00:03<00:08, 4.41MB/s]

 24%|██▍       | 11.0M/45.8M [00:03<00:07, 4.58MB/s]

 26%|██▌       | 12.0M/45.8M [00:03<00:07, 4.63MB/s]

 28%|██▊       | 13.0M/45.8M [00:04<00:07, 4.74MB/s]

 31%|███       | 14.0M/45.8M [00:04<00:06, 4.88MB/s]

 33%|███▎      | 15.0M/45.8M [00:04<00:06, 4.75MB/s]

 35%|███▍      | 16.0M/45.8M [00:04<00:06, 4.88MB/s]

 37%|███▋      | 17.0M/45.8M [00:04<00:06, 5.00MB/s]

 39%|███▉      | 18.0M/45.8M [00:05<00:05, 5.04MB/s]

 41%|████▏     | 19.0M/45.8M [00:05<00:06, 4.29MB/s]

 44%|████▎     | 20.0M/45.8M [00:05<00:05, 4.83MB/s]

 46%|████▌     | 21.0M/45.8M [00:05<00:05, 4.62MB/s]

 48%|████▊     | 22.0M/45.8M [00:06<00:05, 4.49MB/s]

 50%|█████     | 23.0M/45.8M [00:06<00:06, 3.84MB/s]

 52%|█████▏    | 24.0M/45.8M [00:06<00:05, 3.95MB/s]

 55%|█████▍    | 25.0M/45.8M [00:06<00:05, 4.25MB/s]

 57%|█████▋    | 26.0M/45.8M [00:07<00:04, 4.49MB/s]

 59%|█████▉    | 27.0M/45.8M [00:07<00:04, 4.81MB/s]

 61%|██████    | 28.0M/45.8M [00:07<00:04, 4.44MB/s]

 63%|██████▎   | 29.0M/45.8M [00:07<00:03, 4.71MB/s]

 66%|██████▌   | 30.0M/45.8M [00:07<00:03, 4.85MB/s]

 68%|██████▊   | 31.0M/45.8M [00:08<00:03, 4.85MB/s]

 70%|██████▉   | 32.0M/45.8M [00:08<00:02, 4.97MB/s]

 72%|███████▏  | 33.0M/45.8M [00:08<00:02, 4.97MB/s]

 74%|███████▍  | 34.0M/45.8M [00:08<00:02, 5.04MB/s]

 76%|███████▋  | 35.0M/45.8M [00:09<00:02, 4.47MB/s]

 79%|███████▊  | 36.0M/45.8M [00:09<00:02, 4.54MB/s]

 81%|████████  | 37.0M/45.8M [00:09<00:01, 4.66MB/s]

 83%|████████▎ | 38.0M/45.8M [00:09<00:01, 4.58MB/s]

 85%|████████▌ | 39.0M/45.8M [00:09<00:01, 4.65MB/s]

 87%|████████▋ | 40.0M/45.8M [00:10<00:01, 4.61MB/s]

 90%|████████▉ | 41.0M/45.8M [00:10<00:01, 4.60MB/s]

 92%|█████████▏| 42.0M/45.8M [00:10<00:00, 4.44MB/s]

 94%|█████████▍| 43.0M/45.8M [00:10<00:00, 4.44MB/s]

 96%|█████████▌| 44.0M/45.8M [00:11<00:00, 4.41MB/s]

 98%|█████████▊| 45.0M/45.8M [00:11<00:00, 4.50MB/s]

100%|██████████| 45.8M/45.8M [00:11<00:00, 4.50MB/s]

100%|██████████| 45.8M/45.8M [00:11<00:00, 4.16MB/s]

Extracting files...

Data downloaded to :  ../data/M5-Walmart-Sales-Forecasting/

# 5 . Check the Downloaded Files :-

The [Kaggle data page](https://www.kaggle.com/competitions/m5-forecasting-accuracy/data) describes the 5 files as :
- **calendar.csv :** the dates on which the products are sold, with events and SNAP days
- **sales_train_validation.csv :** daily units sold per product and store, days `d_1` to `d_1913`
- **sales_train_evaluation.csv :** the same sales with **28** more days, `d_1` to `d_1941`
- **sell_prices.csv :** the price of each product per store and week
- **sample_submission.csv :** the format for sending forecasts to the competition

The cells below check the files on disk.

In [5]:
for i in sorted(os.listdir(DATA_DIR)):                                    # loop over the files in the folder
    if i.endswith('.csv'):
        size = os.path.getsize(DATA_DIR + i) / 1e6                        # file size in MB
        print(i, ":", round(size, 1), "MB")

missing = [i for i in FILES if not os.path.exists(DATA_DIR + i)]          # needed files that are not there
print("\nMissing files : ", missing)

calendar.csv : 0.1 MB
sales_train_evaluation.csv : 121.7 MB
sales_train_validation.csv : 120.0 MB
sample_submission.csv : 5.2 MB
sell_prices.csv : 203.4 MB

Missing files :  []

### Insights :-
- Kaggle gives **5** csv files and none of them is missing.
- `sell_prices.csv` is the biggest file (**203.4 MB**), `calendar.csv` is the smallest (**0.1 MB**).
- There are two sales files, so we check which one to use.

## ( i ) . Which Sales File to Use :-

There are two sales files. First we look at the first rows of both, then we compare them to decide which one we need.

In [6]:
val = pd.read_csv(DATA_DIR + 'sales_train_validation.csv', nrows=5)          # read only the first 5 rows
val

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1904,d_1905,d_1906,d_1907,d_1908,d_1909,d_1910,d_1911,d_1912,d_1913
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,3,0,1,1,1,3,0,1,1
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,2,1,1,1,0,1,1,1
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,5,4,1,0,1,3,7,2
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,1,1,0,1,1,2,2,2,4

In [7]:
eva = pd.read_csv(DATA_DIR + 'sales_train_evaluation.csv', nrows=5)          # read only the first 5 rows
eva

,id,item_id,dept_id,cat_id,store_id,state_id,d_1,d_2,d_3,d_4,...,d_1932,d_1933,d_1934,d_1935,d_1936,d_1937,d_1938,d_1939,d_1940,d_1941
0,HOBBIES_1_001_CA_1_evaluation,HOBBIES_1_001,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,2,4,0,0,0,0,3,3,0,1
1,HOBBIES_1_002_CA_1_evaluation,HOBBIES_1_002,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,1,2,1,1,0,0,0,0,0
2,HOBBIES_1_003_CA_1_evaluation,HOBBIES_1_003,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,0,2,0,0,0,2,3,0,1
3,HOBBIES_1_004_CA_1_evaluation,HOBBIES_1_004,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,1,1,0,4,0,1,3,0,2,6
4,HOBBIES_1_005_CA_1_evaluation,HOBBIES_1_005,HOBBIES_1,HOBBIES,CA_1,CA,0,0,0,0,...,0,0,0,2,1,0,0,2,1,0

### Insights :-
- Each row is **one product in one store** (`item_id` and `store_id`), with its department, category and state.
- Each day is a **column** : `d_1`, `d_2`, ... up to `d_1913` in the validation file and up to `d_1941` in the evaluation file.
- The validation file has **1,919** columns and the evaluation file **1,947**, the first **6** describe the product and the rest are days.
- So we compare the two files on their products (rows) and their days (columns).

In [8]:
val_days = [i for i in val.columns if i.startswith('d_')]                   # day columns of validation file
eva_days = [i for i in eva.columns if i.startswith('d_')]                   # day columns of evaluation file

## products of all rows, only the 2 product columns are read
val_products = pd.read_csv(DATA_DIR + 'sales_train_validation.csv', usecols=['item_id', 'store_id'])
eva_products = pd.read_csv(DATA_DIR + 'sales_train_evaluation.csv', usecols=['item_id', 'store_id'])

## sales of the common days d_1 to d_1913 from both files (int16 keeps the memory small)
val_sales = pd.read_csv(DATA_DIR + 'sales_train_validation.csv', usecols=val_days, dtype='int16')
eva_sales = pd.read_csv(DATA_DIR + 'sales_train_evaluation.csv', usecols=val_days, dtype='int16')

print("Products in validation file   : ", val_products.shape[0])
print("Products in evaluation file   : ", eva_products.shape[0])
print("Same products in both files   : ", val_products.equals(eva_products))
print("Days in validation file       : ", len(val_days), "(", val_days[0], "to", val_days[-1], ")")
print("Days in evaluation file       : ", len(eva_days), "(", eva_days[0], "to", eva_days[-1], ")")
print("Same sales on the common days : ", val_sales.equals(eva_sales))

Products in validation file   :  30490
Products in evaluation file   :  30490
Same products in both files   :  True
Days in validation file       :  1913 ( d_1 to d_1913 )
Days in evaluation file       :  1941 ( d_1 to d_1941 )
Same sales on the common days :  True

### Insights :-
- Both files have the same **30,490** products.
- The evaluation file has **1,941** days and the validation file **1,913**, so the evaluation file has **28** more days at the end.
- The sales of the common days `d_1` to `d_1913` are exactly the same in both files.
- So the evaluation file has everything the validation file has, and we use only `sales_train_evaluation.csv`. `sample_submission.csv` is only the Kaggle submission format, so it is not needed either.

# ----- CONCLUSION -----

- The M5 dataset is downloaded into `data/M5-Walmart-Sales-Forecasting/`.
- The project uses **3** files : `sales_train_evaluation.csv` (daily sales), `calendar.csv` (dates, events and SNAP days) and `sell_prices.csv` (weekly prices).